import { AppState, Student } from './types';
import { getTodayStr } from './utils/helpers';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: '15052012',
    name: 'Nguyễn Văn An',
    dob: '2012-05-15',
    gender: 'Nam',
    parentName: 'Nguyễn Văn Ba',
    phone: '0912345678',
    address: '12 Phố Huế, Hai Bà Trưng, Hà Nội',
    avatar: '',
    password: '15052012',
    grades: {
      Toán: 8.5,
      'Ngữ văn': 7.8,
      'Tiếng Anh': 8.2,
      KHTN: 8.0,
      'LS&ĐL': 7.5,
      GDCD: 9.0,
      'Tin học': 9.2,
      'Công nghệ': 8.0,
      'Thể dục': 8.5,
    },
  },
  {
    id: '20082012',
    name: 'Trần Thị Bình',
    dob: '2012-08-20',
    gender: 'Nữ',
    parentName: 'Trần Văn Tuấn',
    phone: '0987654321',
    address: '45 Cầu Giấy, Cầu Giấy, Hà Nội',
    avatar: '',
    password: '20082012',
    grades: {
      Toán: 9.0,
      'Ngữ văn': 9.2,
      'Tiếng Anh': 9.5,
      KHTN: 8.8,
      'LS&ĐL': 9.0,
      GDCD: 9.5,
      'Tin học': 9.0,
      'Công nghệ': 8.5,
      'Thể dục': 8.0,
    },
  },
  {
    id: '10112012',
    name: 'Lê Hoàng Châu',
    dob: '2012-11-10',
    gender: 'Nữ',
    parentName: 'Lê Hoàng Hải',
    phone: '0903344556',
    address: '88 Kim Mã, Ba Đình, Hà Nội',
    avatar: '',
    password: '10112012',
    grades: {
      Toán: 8.0,
      'Ngữ văn': 8.5,
      'Tiếng Anh': 8.8,
      KHTN: 8.2,
      'LS&ĐL': 8.0,
      GDCD: 8.5,
      'Tin học': 8.0,
      'Công nghệ': 8.0,
      'Thể dục': 8.0,
    },
  },
  {
    id: '03022012',
    name: 'Phạm Đình Dũng',
    dob: '2012-02-03',
    gender: 'Nam',
    parentName: 'Phạm Văn Hùng',
    phone: '0919988776',
    address: '32 Khâm Thiên, Đống Đa, Hà Nội',
    avatar: '',
    password: '03022012',
    grades: {
      Toán: 6.8,
      'Ngữ văn': 6.5,
      'Tiếng Anh': 6.0,
      KHTN: 7.0,
      'LS&ĐL': 6.5,
      GDCD: 8.0,
      'Tin học': 7.5,
      'Công nghệ': 7.0,
      'Thể dục': 8.5,
    },
  },
  {
    id: '18092012',
    name: 'Hoàng Thu Hằng',
    dob: '2012-09-18',
    gender: 'Nữ',
    parentName: 'Hoàng Minh Đức',
    phone: '0977112233',
    address: '56 Lê Duẩn, Hoàn Kiếm, Hà Nội',
    avatar: '',
    password: '18092012',
    grades: {
      Toán: 9.2,
      'Ngữ văn': 9.0,
      'Tiếng Anh': 9.6,
      KHTN: 9.0,
      'LS&ĐL': 8.8,
      GDCD: 9.5,
      'Tin học': 9.5,
      'Công nghệ': 9.0,
      'Thể dục': 8.5,
    },
  },
  {
    id: '25122012',
    name: 'Đỗ Đức Kiên',
    dob: '2012-12-25',
    gender: 'Nam',
    parentName: 'Đỗ Tiến Dũng',
    phone: '0934567890',
    address: '15 Trần Duy Hưng, Cầu Giấy, Hà Nội',
    avatar: '',
    password: '25122012',
    grades: {
      Toán: 7.5,
      'Ngữ văn': 7.0,
      'Tiếng Anh': 7.2,
      KHTN: 7.5,
      'LS&ĐL': 7.0,
      GDCD: 8.5,
      'Tin học': 8.0,
      'Công nghệ': 7.5,
      'Thể dục': 9.0,
    },
  },
  {
    id: '09042012',
    name: 'Vũ Thảo Linh',
    dob: '2012-04-09',
    gender: 'Nữ',
    parentName: 'Vũ Đình Quang',
    phone: '0988223344',
    address: '27 Chùa Bộc, Đống Đa, Hà Nội',
    avatar: '',
    password: '09042012',
    grades: {
      Toán: 8.8,
      'Ngữ văn': 8.5,
      'Tiếng Anh': 8.9,
      KHTN: 8.6,
      'LS&ĐL': 8.2,
      GDCD: 9.0,
      'Tin học': 8.5,
      'Công nghệ': 8.0,
      'Thể dục': 8.0,
    },
  },
  {
    id: '14072012',
    name: 'Bùi Minh Quân',
    dob: '2012-07-14',
    gender: 'Nam',
    parentName: 'Bùi Xuân Thắng',
    phone: '0945671234',
    address: '90 Hoàng Hoa Thám, Ba Đình, Hà Nội',
    avatar: '',
    password: '14072012',
    grades: {
      Toán: 6.5,
      'Ngữ văn': 6.0,
      'Tiếng Anh': 6.2,
      KHTN: 6.8,
      'LS&ĐL': 6.5,
      GDCD: 7.5,
      'Tin học': 7.0,
      'Công nghệ': 7.0,
      'Thể dục': 8.5,
    },
  },
];

const today = getTodayStr();

export const DEFAULT_INITIAL_STATE: AppState = {
  config: {
    appName: 'Trợ lý chủ nhiệm',
    className: '9A5',
    schoolYear: '2026-2027',
    teacherName: 'Nguyễn Thị Diễm Hương',
    teacherPassword: 'admin',
    classAvatar: '',
    availableClasses: ['9A5', '8A3', '7A1', '6A2'],
    subjects: [
      'Toán',
      'Ngữ văn',
      'Tiếng Anh',
      'KHTN',
      'LS&ĐL',
      'GDCD',
      'Tin học',
      'Công nghệ',
      'Thể dục',
    ],
    rules: [
      { id: 'r1', name: 'Đi học muộn', points: 2, type: 'minus' },
      { id: 'r2', name: 'Không làm bài tập', points: 5, type: 'minus' },
      { id: 'r3', name: 'Không mang dụng cụ học tập', points: 2, type: 'minus' },
      { id: 'r4', name: 'Vi phạm đồng phục / tác phong', points: 2, type: 'minus' },
      { id: 'r5', name: 'Nói chuyện riêng trong giờ', points: 3, type: 'minus' },
      { id: 'r6', name: 'Sử dụng điện thoại trong giờ học', points: 5, type: 'minus' },
      { id: 'r7', name: 'Nghỉ học không phép', points: 5, type: 'minus' },
      { id: 'r8', name: 'Phát biểu xây dựng bài sôi nổi', points: 1, type: 'plus' },
      { id: 'r9', name: 'Đạt điểm 10 kiểm tra', points: 3, type: 'plus' },
      { id: 'r10', name: 'Nhặt được của rơi trả người đánh mất', points: 5, type: 'plus' },
      { id: 'r11', name: 'Tham gia tích cực phong trào lớp', points: 2, type: 'plus' },
    ],
    conductThresholds: { good: 0, fair: -5, average: -10 },
  },
  students: INITIAL_STUDENTS,
  seatingLayout: {
    groups: 4,
    rows: 8,
    seatsPerTable: 2,
  },
  seatingChart: {
    'g1-r1-s1': '15052012',
    'g1-r1-s2': '20082012',
    'g2-r1-s1': '10112012',
    'g2-r1-s2': '03022012',
    'g3-r1-s1': '18092012',
    'g3-r1-s2': '25122012',
    'g4-r1-s1': '09042012',
    'g4-r1-s2': '14072012',
  },
  attendance: [
    { id: 'att-1', studentId: '15052012', date: today, status: 'c' },
    { id: 'att-2', studentId: '20082012', date: today, status: 'c' },
    { id: 'att-3', studentId: '10112012', date: today, status: 'c' },
    { id: 'att-4', studentId: '03022012', date: today, status: 'm' },
    { id: 'att-5', studentId: '18092012', date: today, status: 'c' },
    { id: 'att-6', studentId: '25122012', date: today, status: 'c' },
    { id: 'att-7', studentId: '09042012', date: today, status: 'c' },
    { id: 'att-8', studentId: '14072012', date: today, status: 'v' },
  ],
  discipline: [
    {
      id: 'd-1',
      studentId: '18092012',
      date: today,
      ruleId: 'r9',
      ruleName: 'Đạt điểm 10 kiểm tra',
      points: 3,
      type: 'plus',
      note: 'Điểm 10 kiểm tra 15 phút môn Toán',
    },
    {
      id: 'd-2',
      studentId: '20082012',
      date: today,
      ruleId: 'r8',
      ruleName: 'Phát biểu xây dựng bài sôi nổi',
      points: 1,
      type: 'plus',
      note: 'Hăng hái phát biểu giờ Tiếng Anh',
    },
    {
      id: 'd-3',
      studentId: '03022012',
      date: today,
      ruleId: 'r1',
      ruleName: 'Đi học muộn',
      points: 2,
      type: 'minus',
      note: 'Đi học muộn 15 phút tiết 1',
    },
    {
      id: 'd-4',
      studentId: '14072012',
      date: today,
      ruleId: 'r2',
      ruleName: 'Không làm bài tập',
      points: 5,
      type: 'minus',
      note: 'Quên làm bài tập Ngữ văn',
    },
  ],
  notes: [
    {
      id: 'n-1',
      studentId: '03022012',
      date: today,
      type: 'Liên hệ PH',
      content: 'Đã nhắn tin cho phụ huynh nhắc nhở tình trạng đi học muộn.',
    },
    {
      id: 'n-2',
      studentId: '18092012',
      date: today,
      type: 'Học tập',
      content: 'Học tập rất tiến bộ, đề xuất vào đội tuyển Toán.',
    },
  ],
  boardNotices: [
    {
      id: 'bn-1',
      date: today,
      title: 'Lịch thi giữa học kỳ I',
      content:
        'Nhắc nhở cả lớp chuẩn bị ôn tập cho kỳ thi giữa kỳ I bắt đầu từ thứ Hai tuần sau. Các em chú ý nắm vững đề cương ôn tập các môn.',
      type: 'warning',
    },
    {
      id: 'bn-2',
      date: today,
      title: 'Khen thưởng phong trào Báo tường 20/11',
      content:
        'Biểu dương tập thể lớp đã hoàn thành xuất sắc sản phẩm Báo tường chào mừng Ngày Nhà giáo Việt Nam và đạt giải Nhì toàn trường!',
      type: 'success',
    },
    {
      id: 'bn-3',
      date: today,
      title: 'Thu thập thông tin BHYT học sinh',
      content:
        'Phụ huynh vui lòng kiểm tra và gửi lại bản photo thẻ BHYT có giá trị sử dụng cho giáo viên chủ nhiệm trước ngày 15/10.',
      type: 'info',
    },
  ],
};
